# Generated by Django 4.1.4 on 2023-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
